### PR TITLE
Add 'whatisthis' modal to landing

### PR DESCRIPTION
**Pull request by heatherbooker**
looks like:
here

let me know what if anything youd like to see changed before i merge @ebb-tide

### CODE REVIEW

**Comment by ebb-tide** [comment]
looking awesome !
could the links be pink? 
and could there be a bit more space at the top and on the sides? I really like the sparse look of the site. 
merge away!

**Comment by heatherbooker** [comment]
@ebb-tide is this good? if you like it, go ahead and merge and close the issue! whee! screenshot of modal

**Comment by ebb-tide** [comment]
beautiful!
Could the whole modal be a little lower on the screen?
that's it.
merge! merge!

**Comment by ebb-tide** [comment]
so I pulled from the server, and it doesn't seem to work yet. the what is this button seems to be pointing towards whatisthis.html ? I didn't want to meddle, so fyi. 
I'd also like to be able to check if you can pull from the server with your account, so could you try taking this all the way to production?

**Pull request merged**
